heat_template_version: 2015-10-15
description: Launch a basic instance with CirrOS image using the
             ``m1.tiny`` flavor, ``mykey`` key,  and one network.

#parameters:
#  NetID:
#    type: string
#    description: Network ID to use for the instance.

resources:
  server:
    type: OS::Nova::Server
    properties:
      image: cirros
      flavor: m1.tiny
      key_name: my_key
      security_groups:
        - security-server-web_secgroup-jcjdfi5uwszk
      networks:
      - network: fa338809-dc8d-4a2a-b4cb-0f15639fab8b

outputs:
  instance_name:
    description: Name of the instance.
    value: { get_attr: [ server, name ] }
  instance_ip:
    description: IP address of the instance.
    value: { get_attr: [ server, first_address ] }

